version: "3.8"

networks:
  jenkins:
    driver: bridge

services:
  jenkins_server:
    build:
      context: .
    networks:
      - jenkins
    container_name: JenkinsServer
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home:rw
      - ./jenkins-docker-certs:/certs/client:ro
      - ./extras:/extras:rw

  jenkins_docker:
    image: docker:dind
    networks:
      jenkins:
        aliases:
          - docker
    container_name: JenkinsDocker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - "2376:2376"
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
      - ./extras:/extras
